from pulsar.schema import *

class Stock(Record):
    symbol = String()
    exchange_id = Integer()
    trade_id = Integer()
    price = Float()
    size = Integer()
    tape = Integer()
    time = Long()

class Features(Record):
    symbol = String()
    avg_1 = Float()
    avg_5 = Float()
    avg_10 = Float()
    avg_15 = Float()
    avg_30 = Float()
    avg_60 = Float()
    avg_120 = Float()
    avg_240 = Float()
    avg_480 = Float()
    avg_960 = Float()
    avg_1440 = Float()
    stddev_1 = Float()
    stddev_5 = Float()
    stddev_10 = Float()
    stddev_15 = Float()
    stddev_30 = Float()
    stddev_60 = Float()
    stddev_120 = Float()
    stddev_240 = Float()
    stddev_480 = Float()
    stddev_960 = Float()
    stddev_1440 = Float()
    vol_1 = Float()
    vol_5 = Float()
    vol_10 = Float()
    vol_15 = Float()
    vol_30 = Float()
    vol_60 = Float()
    vol_120 = Float()
    vol_240 = Float()
    vol_480 = Float()
    vol_960 = Float()
    vol_1440 = Float()
